# Generated by Django 5.2.7 on 2025-10-16 17:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Versión amigable para URL del título, ej: mi-primer-proyecto', max_length=200, unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('results', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('image', models.URLField(max_length=500)),
                ('demo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
